# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, verbose_name='⽬标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最⼩查找范围')),
                ('max_distance', models.IntegerField(default=10, verbose_name='最⼤查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最⼩交友年龄')),
                ('max_dating_age', models.IntegerField(default=30, verbose_name='最⼤交友年龄')),
                ('dating_sex', models.CharField(choices=[('M', '男'), ('W', '女')], max_length=8, verbose_name='匹配的性别')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_matche', models.BooleanField(default=True, verbose_name='不让为匹配的⼈看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='⾃动播放视频')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenu', models.CharField(max_length=16, unique=True, verbose_name='⼿机号')),
                ('nickname', models.CharField(max_length=24, unique=True, verbose_name='昵称')),
                ('sex', models.CharField(choices=[('M', '男'), ('W', '女')], max_length=8, verbose_name='性别')),
                ('birth_year', models.IntegerField(default=2000, verbose_name='出⽣年')),
                ('birth_month', models.IntegerField(default=1, verbose_name='出⽣⽉')),
                ('birth_day', models.IntegerField(default=1, verbose_name='出⽣⽇')),
                ('avatar', models.CharField(max_length=256, verbose_name='个⼈形象URL')),
                ('location', models.CharField(max_length=64, verbose_name='常居地')),
            ],
        ),
    ]
